
modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPLv3"

[[mods]]
modId = "thequestforge"
version = "0.0.1"
displayName = "The Quest Forge"
logoFile = "thequestforge_logo.png"
credits = "Noyji"
authors = "noyji"

description = '''
The Quest Forge is a comprehensive mod and API for creating RPG quests.
It adds a user-friendly dialogue system with NPCs, flexible configuration of requirements,
tasks (collecting items, killing mobs), and rewards.
'''

[[dependencies.thequestforge]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thequestforge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"